Sp01-H01 / Criação de Landing Page responsiva (seção "Conheça nossos projetos")
compiladoras/Plataforma pull request #15
Opened 2021-10-27 13:35 UTC by IsabellaSoares

## Descrição

Este PR adiciona na Landing Page a seção **"Conheça nossos projetos"**. Tratando-se da primeira issue referente à criação da Landing Page responsiva, este PR também adiciona alguns componentes iniciais do projeto. Na seção "Conheça nossos projetos" temos a listagem dos projetos da comunidade. Na versão desktop temos um carrossel com os cards, enquanto na versão mobile (até 720px) temos uma listagem desses cards. Ao clicar nos botões dos cards, os usuários devem ser redirecionados para os respectivos links onde podem se inscrever/solicitar acesso nos canais dos projetos.

**Páginas**

- Landing Page

**Componentes**

- Button
- Card (projetos)
- Carousel
- Content container (para padronizar o conteúdo de todas as seções da página)
- Icons
- Title

## Issue relacionada

_sp01-h01-Criação de Landing page responsiva (Conheça nossos projetos)_

## Critérios de aceite

## Tipo de mudança

|     | Type                               |
| --- | ---------------------------------- |
|     | :bug: Correção de bug              |
|  ✓  | :sparkles: Nova feature            |
|     | :hammer: Refatoração               |
|     | :100: Adição de testes             |
|     | :link: Atualização de dependências |
|     | :scroll: Documentação              |

## Atualizações

### Desktop

![desktop](https://user-images.githubusercontent.com/32148199/139074621-046d7ece-c8f8-47f9-a17f-89fc6e0f5968.gif)

### Tablet (720px - 992px)

![tablet](https://user-images.githubusercontent.com/32148199/139074650-57a450f3-224e-4d72-99ca-ab61a1b15662.gif)

### Mobile (até 720px)

![mobile](https://user-images.githubusercontent.com/32148199/139074660-98a74e2e-a9c1-4447-ba02-55c5c8472c60.gif)

## Passos de teste / Critérios de QA

Para testar é necessário iniciar o projeto e conferir o comportamento da aplicação das três dimensões:

- **Mobile:** até 720px, onde os cards devem aparecer como uma lista
- **Tablet:** entre 720px e 992px, onde temos um carrossel com apenas um card ativo
- **Desktop**: a partir de 992px, onde temos um carrossel com dois cards ativos

**Critérios de QA**

- [x] Dado que	a página da Plataforma Compiladoras é responsiva, quando uma usuária acessar a página pelo celular o conteúdo e a página deverão se adaptar automaticamente ao tamanho do dispositivo que fez a chamada
- [x] Dado que	a página da Plataforma Compiladoras é responsiva quando uma usuária acessar a página pelo desktop o conteúdo e a página deverão se adaptar automaticamente ao tamanho do dispositivo que fez a chamada

2021-10-27 21:18 UTC, BiancaPereira commented on .eslintrc.json
> +		"@typescript-eslint/explicit-module-boundary-types": "off"
Essa regra aqui, eu acho interessante forçar a tipagem de retorno de uma função. 
Estava dando algum conflito chato com o React?

2021-10-27 21:19 UTC, BiancaPereira commented on .eslintrc.json
> +		],
Essa regra de no shadow eu acho bacana, porque evita de ficar usando o mesmo nome de variável em diversos locais do código. Estava dando algum conflito com o React? Teve um motivo pra desligar essa validação?

2021-10-27 21:21 UTC, BiancaPereira commented on src/components/carousel/Slider.tsx
> +      sliderRef.current ? Math.ceil(sliderRef.current.offsetWidth) : 0,
Por que usou offset witdth aqui?

Não sei se precisávamos da biblioteca lodash nesse ponto

2021-10-27 21:26 UTC, BiancaPereira commented on src/components/button/button.style.ts
> +  border: 2px solid #fe393b;
Seria interessante criar um arquivo de cores padronizadas pra forçar um padrão de cores e forçar seguir as cores do protótipo, o que acha?

Exemplo, seria mais ou menos assim:

**colors.js**

```
const colors = {
 red: #FF0000;
} 

export default colors;
```

Aí para usar seria:

```
import * from './colors.js;
...
background: colors.red
```

Eu gosto de usar essa abordagem num geral, pensando mais num contexto de forçar a padronização tanto no front, quanto no UX também. A gente pode definir essas variáveis pra um monte de coisa, inclusive para espaçamento

Tipo: `padding: 16px` seria o spacing-md, ai teria spacing-sm, etc

O que acha? Faz sentido? Se você achar que não seria interessante ou que a gente perderia tempo e não seria mto efetivo, eu queria saber a sua opinião!

2021-10-27 21:28 UTC, BiancaPereira commented on src/components/button/button.style.ts
> +  font-weight: 700;
No comentário que comentei acima, também poderia ter um arquivo de padrões de font-weight

2021-10-27 21:29 UTC, BiancaPereira commented on src/components/card/card.style.ts
> +  box-shadow: 4px 4px 6px rgba(0, 0, 0, 0.1);
Dependendo das sombras e das bordas e como elas são usadas no sistema, daria para colocar uma padronização aqui tbm

2021-10-27 21:29 UTC, BiancaPereira commented on src/components/card/card.style.ts
> +  @media screen and (max-width: 720px) {
Esses breakpoints também poderiam ser padronizados em variáveis

2021-10-27 21:31 UTC, BiancaPereira commented on src/components/card/card.style.ts
> +  line-height: 30px;
O line height também. Eu gosto de usar os line-heights tbm como porcentagem, tipo: 1.5 (seria 50% maior que o tamanho da fonte)

No figma não fica assim, né? Ficaria um pouco complicado de fazer essas medidas/cálculos, mas podemos falar sobre

2021-10-27 21:35 UTC, BiancaPereira commented on src/components/carousel/Slider.tsx
> +    const preCloneNo = slideCount - index;
esse `No` seria de `Number`? Seria interessante colocar por extenso aqui, porque pode causar confusão na leitura

2021-10-27 21:40 UTC, BiancaPereira commented on src/components/carousel/Swipeable.tsx
> +        if (onSwipe) onSwipe(getSwipeDirection(swipingState.movementX));
Aqui ficou um pouco confuso de ler... não daria pra colocar todas as condições ou pelo menos 2 no mesmo `if`?

Eu digo isso pq quando tem if's usando chaves `{}` e um no meio que não usa, pode gerar uma confusão a princípio pra ler o código. No geral eu não uso sem as chaves por conta da legibilidade mesmo. 

O que acha? Se vc achar tranquilo de usar, eu acho que não ficou tão difícil pra ler essa parte, mas quero saber o que pensa sobre

2021-10-27 21:49 UTC, BiancaPereira commented on src/components/carousel/helpers.ts
> +    slideWidth = Math.ceil(sliderWidth / slidesToShow);
Nesse `slideWidth` não seria melhor mudar ela pra `newSlideWitdh` ou aplicar ela em algum estado usando um `useState`? Assim não precisaria sobreescrever ela e poderia remover o `/* eslint-disable no-param-reassign */`

2021-10-27 21:54 UTC, BiancaPereira commented on src/components/icon/icon.tsx
> +          key={index}
O que acha de usar a "key" como o próprio "path" + um número random? Ou mesmo o próprio "index" e um número random também

Nesse caso, a key poderia ser repetida na mesma renderização de um componente, se tiver mais de 2 ícones

Exemplo: eles ficariam como

`<icon key="1">` e `<icon (outro icon) key="1">` também

Quando tem dois componentes com o mesmo key, pode dar ruim na tela

O que acha? Faz sentido? Eu não sei se esse caso que comentei seria possível (de ter 2 componentes iguais na mesma tela). Mas lembro que estudei q podia dar ruim ao renderizar a tela se tivesse componentes com a mesma key e realizar alguma ação neles (tipo ação de click) e outras interações com o usuário

2021-10-27 21:56 UTC, BiancaPereira commented on src/components/icon/icons.ts
> +    ],
Podemos salvar esses SVGs numa pasta de assets ou imgs? Esse arquivo acabou ficando grande demais e provavelmente iremos reutilizar esses SVGs em outras telas tbm, ter cada um num arquivinho diferente facilitaria no futuro

2021-10-27 21:57 UTC, BiancaPereira commented on src/pages/landing-page.tsx
> +          size: 991,
Fixar esses breakpoints em alguma constante/variável

2021-10-27 21:57 UTC, BiancaPereira requested changes
Analisar comentários

2021-10-28 02:29 UTC, IsabellaSoares commented on src/components/button/button.style.ts
> +  border: 2px solid #fe393b;
Eu acho a ideia ótima! Inclusive cheguei a conversar sobre isso com a @marcela093, mas como esta task estava demandando muito tempo e o PR ficou grande, pensamos que seria melhor deixar essa refatoração para a próxima sprint e criar uma task dedicada só para isso. O que você acha? Levamos para a próxima sprint ou caberia neste PR mesmo?

2021-10-28 02:31 UTC, IsabellaSoares commented on src/components/carousel/Swipeable.tsx
> +        if (onSwipe) onSwipe(getSwipeDirection(swipingState.movementX));
Concordo que realmente ficou confuso. Vou refatorar essa parte.

2021-10-28 02:34 UTC, IsabellaSoares commented on src/components/icon/icon.tsx
> +          key={index}
Faz total sentido! Não tinha pensando nisso. Acredito que pode acontecer sim, principalmente por conta dos cards dos projetos, os ícones dos botões são iguais em alguns casos. Vou arrumar isso também!

2021-10-28 02:34 UTC, IsabellaSoares commented on src/components/icon/icons.ts
> +    ],
Você diz colocar esses paths em arquivos separados ou adicionar no projeto os arquivos `.svg` reais?

2021-10-28 02:38 UTC, IsabellaSoares commented on src/components/carousel/Slider.tsx
> +    const preCloneNo = slideCount - index;
Exatamente! Você tem razão, vou corrigir isso!

2021-10-28 02:52 UTC, IsabellaSoares commented on src/components/carousel/helpers.ts
> +    slideWidth = Math.ceil(sliderWidth / slidesToShow);
Na verdade, o erro `/* eslint-disable no-param-reassign */` não estava neste trecho, estava neste aqui `previousActive = current += childrenCount;`. Não há a necessidade de sobrecrever o valor de `current`. Corrigindo esse trecho já não preciso desabilitar essa regra do eslint. No caso da variável `slideWidth`, não temos conflito porque o parâmetro se chama `sliderWidth`. Ainda assim, você acha que seria melhor renomear essa variável para ficar mais inteligível?

2021-10-28 13:08 UTC, IsabellaSoares commented on .eslintrc.json
> +		"@typescript-eslint/explicit-module-boundary-types": "off"
Estava sim, mas eu já arrumei e habilitei a regra de novo!

2021-10-28 13:25 UTC, IsabellaSoares commented on src/components/carousel/Slider.tsx
> +      sliderRef.current ? Math.ceil(sliderRef.current.offsetWidth) : 0,
Usei o `offsetWidth` para conseguir determinar o tamanho do slider de acordo com o tamanho necessário para os cards. Sem ele não consegui definir o tamanho certo e os cards ficam quebrados.

2021-11-01 18:42 UTC, marcela093 approved these changes

2021-11-03 19:52 UTC, BiancaPereira approved these changes

2021-11-03 19:53 UTC, merged