Sp01-H02 / Header
compiladoras/Plataforma pull request #17
Opened 2021-11-01 17:56 UTC by marcela093

2021-11-01 21:56 UTC, IsabellaSoares requested changes
Amiga, o header ficou show de bola! Parabéns! Mas eu notei algumas coisas, por isso estou pedindo por alterações.

Notei que existe um arquivo em `src/assets/header.png` que não sei onde você está utilizando. Não sei se você esqueceu de excluir ele ou eu não notei no PR.

No PR #15 optamos por manter a regra do ESLint que pede tipagem de retorno nas funções. Como os seus componentes não têm retorno, fica aparecendo erro no terminal, daí sugeri que você adicione os tipos de retorno.

Fico aguardando sua opinião sobre as sugestões de melhoria, então eu dou approve aqui! Abraços! ❤️

2021-11-01 21:56 UTC, IsabellaSoares commented on src/components/heart/heart.tsx
> +};
Sei que temos a pasta de ícones e lá tratamos de arquivos .svg, mas fiquei pensando se esse carinha também não deveria estar lá? Ele é um ícone animado e tem todo esse estilo de componente, mas ainda é um ícone. Não vejo problema em ficar aqui, mas achei interessante levantar essa discusão

2021-11-01 21:56 UTC, IsabellaSoares commented on src/components/nav/nav.style.ts
> +  // min-width: 50%;
Esqueceu o comentário 😅

2021-11-01 21:56 UTC, IsabellaSoares commented on src/components/header-button/header-button-style.ts
> +  font-size: 1rem;
Quando começarmos a task sobre os tokens de tema, precisamos definir se vamos utilizar `px` ou `rem` como unidade de medida. Deixando esse comentário só para registrar aqui, e talvez já abrirmos a discussão sobre assunto. Nesse momento pra mim não é nada de mais mantermos assim

2021-11-01 21:56 UTC, IsabellaSoares commented on src/components/nav/nav.style.ts
> +    .desktop {
```suggestion
    .desktop-logo {
```

Que tal colocarmos dessa forma para padronizar?

2021-11-01 21:56 UTC, IsabellaSoares commented on src/pages/landing-page/sections/projects/index.tsx
> +  <ContentContainer id="projetos" className="smooth-scroll">
Não encontrei outras ocorrências da classe `smooth-scroll`, por que está utilizando ela aqui?

2021-11-01 21:56 UTC, IsabellaSoares commented on src/components/header-button/header-button.tsx
> +export const HeaderButton = ({ onClick }: HeaderButtonProps) => {
```suggestion
export const HeaderButton = ({
  onClick,
}: HeaderButtonProps): React.ReactElement => {
```

2021-11-01 21:56 UTC, IsabellaSoares commented on src/components/heart/heart.tsx
> +export const Heart = () => {
```suggestion
export const Heart = (): React.ReactElement => {
```

2021-11-01 21:56 UTC, IsabellaSoares commented on src/components/nav/nav.tsx
> +export const Nav = () => {
```suggestion
export const Nav = (): React.ReactElement => {
```

2021-11-01 21:56 UTC, IsabellaSoares commented on src/icons/compiladoras-desktop-logo.tsx
> +) => {
```suggestion
export const CompiladorasDesktopLogo = (
  props: React.SVGProps<SVGSVGElement>,
): JSX.Element => {
```

2021-11-01 21:56 UTC, IsabellaSoares commented on src/icons/compiladoras-mobile-logo.tsx
> +) => {
```suggestion
export const CompiladorasMobileLogo = (
  props: React.SVGProps<SVGSVGElement>,
): JSX.Element => {
```

2021-11-01 21:56 UTC, IsabellaSoares commented on src/pages/landing-page/sections/header/header.tsx
> +export const Header = () => {
```suggestion
export const Header = (): React.ReactElement => {
```

2021-11-01 21:56 UTC, IsabellaSoares commented on src/icons/heart-icon.tsx
> +export const HeartIcon = (props: React.SVGProps<SVGSVGElement>) => {
```suggestion
export const HeartIcon = (
  props: React.SVGProps<SVGSVGElement>,
): JSX.Element => {
```

2021-11-04 12:14 UTC, marcela093 commented on src/components/heart/heart.tsx
> +};
Faz sentido! Eu deixei ele nos componentes porque eu precisei criar o coração mesmo, não consegui usar o svg, mas não pensei por esse lado rs
Vou mover ele para dentro da pasta de ícones!

2021-11-04 12:20 UTC, marcela093 commented on src/components/nav/nav.style.ts
> +    .desktop {
feito :)

2021-11-04 12:23 UTC, marcela093 commented on src/pages/landing-page/sections/projects/index.tsx
> +  <ContentContainer id="projetos" className="smooth-scroll">
Eu estava tentando fazer uma animação de smooth scroll para quando clicarmos nos menus ele não descer para a section de forma tão bruta (acho que vale deixar mapeado como melhoria), mas acabei não conseguindo e esqueci de remover essa class :)

2021-11-04 13:45 UTC, IsabellaSoares approved these changes

2021-11-04 13:46 UTC, IsabellaSoares commented on src/pages/landing-page/sections/projects/index.tsx
> +  <ContentContainer id="projetos" className="smooth-scroll">
Podemos levantar como melhoria sim, amiga. Temos alguns pequenos ajustes da sprint passada, podemos acrescentar isso também.

2021-11-04 19:01 UTC, BiancaPereira approved these changes

2021-11-04 19:02 UTC, merged

2021-11-04 19:46 UTC, marcela093 commented on src/components/header-button/header-button-style.ts
> +  font-size: 1rem;
boa! :)